import {
  Activity,
  ArrowUpRight,
  Bot,
  Calendar,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleQuestionMark,
  Clock,
  Command,
  Copy,
  Download,
  ExternalLink,
  Eye,
  FileText,
  Folder,
  Funnel,
  GitBranch,
  Inbox,
  Info,
  Layers,
  LayoutDashboard,
  List,
  Menu,
  Minus,
  Moon,
  PanelLeft,
  Plus,
  RefreshCw,
  Search,
  Settings,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tag,
  Terminal,
  Trash,
  TrendingUp,
  TriangleAlert,
  User,
  Workflow,
  X,
  type LucideIcon,
} from 'lucide-react';
import type { IconName } from './types';

export const ICONS: Record<IconName, LucideIcon> = {
  layout: LayoutDashboard,
  activity: Activity,
  bot: Bot,
  workflow: Workflow,
  trending: TrendingUp,
  layers: Layers,
  bars: ChartColumn,
  list: List,
  folder: Folder,
  sparkles: Sparkles,
  sliders: SlidersHorizontal,
  settings: Settings,
  search: Search,
  sun: Sun,
  moon: Moon,
  panel: PanelLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  check: Check,
  x: X,
  clock: Clock,
  download: Download,
  alert: TriangleAlert,
  info: Info,
  arrowUpRight: ArrowUpRight,
  refresh: RefreshCw,
  inbox: Inbox,
  copy: Copy,
  externalLink: ExternalLink,
  filter: Funnel,
  calendar: Calendar,
  tag: Tag,
  gitBranch: GitBranch,
  terminal: Terminal,
  file: FileText,
  help: CircleQuestionMark,
  plus: Plus,
  minus: Minus,
  trash: Trash,
  menu: Menu,
  eye: Eye,
  command: Command,
  user: User,
};
