import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const src = fileURLToPath(new URL('../src/styles/tokens.json', import.meta.url));
const dest = fileURLToPath(new URL('../src/styles/tokens.css', import.meta.url));

const tokens = JSON.parse(readFileSync(src, 'utf8'));
const themes = tokens.color.themes.map((t) => t.id);
const value = (t, theme) => (typeof t.value === 'string' ? t.value : (t.value[theme] ?? t.value[themes[0]]));

function channels(v) {
  const hex = /^#([0-9a-f]{6})$/i.exec(v);
  return hex ? [0, 2, 4].map((i) => parseInt(hex[1].slice(i, i + 2), 16)).join(' ') : null;
}

function block(theme) {
  return [...tokens.color.tokens, ...tokens.shadow.tokens]
    .map((t) => {
      const v = value(t, theme);
      return `  --${t.name}: ${channels(v) ?? v};`;
    })
    .join('\n');
}

const [first, ...rest] = themes;
const css = `/* Generated by scripts/build-tokens.mjs from tokens.json. Colours are RGB channels: rgb(var(--x)) or rgb(var(--x) / <alpha>). */
:root,
:root.${first} {
  color-scheme: ${first};
${block(first)}
}

${rest.map((theme) => `:root.${theme} {\n  color-scheme: ${theme};\n${block(theme)}\n}`).join('\n\n')}
`;

writeFileSync(dest, css);
console.log(`tokens.css: ${tokens.color.tokens.length} colours x ${themes.length} themes`);
